# Uncomment the next line to define a global platform for your project
  platform :ios, '7.0'

target 'iOS Pod Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Pod Example
  pod 'MLAVPlayer', '~>1.0.3'
  pod 'Masonry'
end
